services:
  web:
    image: glitchtip/glitchtip:6 # Check https://glitchtip.com/blog/ for new major versions
    ports:
      - "9001:8000"
    env_file:
      - .env
    environment:
      SERVER_ROLE: all_in_one
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads

volumes:
  uploads:
